name         'stdmod-zimbra'
version      '0.0.1'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-zimbra'
summary      'Puppet module for zimbra'
description  'This module installs and manages zimbra. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
