#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"
# 
mod 'puppetlabs-stdlib'
mod 'puppetlabs-firewall'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-git'
mod 'puppetlabs-inifile'
mod 'puppetlabs-puppetserver_gem'
mod 'puppetlabs-concat'
mod 'puppetlabs-apt'
mod 'puppet-archive'
mod 'saz-locales'
mod 'saz-timezone'
mod 'ghoneycutt-hosts'
mod 'camptocamp-systemd'
mod 'puppetlabs-host_core'
mod 'stm-debconf'
mod 'puppet-zimbra',
  :git => 'https://github.com/Puppet-Finland/puppet-zimbra.git'
mod 'example42-puppi'
mod 'puppet-selinux'
mod 'puppet-unbound'
mod 'saz-resolv_conf'


