#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"
#
# Basic Puppetlabs modules
# 
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-firewall', '1.14.0'
mod 'puppetlabs-vcsrepo', '2.4.0'
mod 'puppetlabs-git', '0.5.0'
mod 'puppetlabs-inifile', '2.4.0'
mod 'puppetlabs-puppetserver_gem', '1.0.0'
mod 'puppetlabs-reboot', '2.0.0'
mod 'puppetlabs-accounts', '3.1.0'
mod 'puppetlabs-java', '6.2.0'
mod 'puppetlabs-java_ks', '2.4.0'
mod 'puppetlabs-apache', '4.0.0'
mod 'puppetlabs-translate', '1.2.0'
mod 'puppetlabs-postgresql', '6.4.0'
mod 'puppetlabs-concat', '5.3.0'
mod 'puppetlabs-apt', '6.3.0'
mod 'puppetlabs-haproxy', '3.0.1'
mod 'puppet-archive', '3.2.1'
mod 'saz-locales', '2.5.1'
mod 'saz-timezone', '5.1.1'
mod 'ghoneycutt-hosts', '2.7.0'
mod 'treydock-keycloak', '6.10.0'
mod 'camptocamp-systemd', '2.9.0'
mod 'puppetlabs-host_core', '1.0.3'
mod 'puppetlabs-mysql', '10.4.0'
mod 'stm-debconf', '2.3.0'
mod 'puppet-zimbra',
  :git => 'https://github.com/Puppet-Finland/puppet-zimbra.git'
mod 'example42-puppi', '2.2.11'

