# Class: zimbra::params
#
# Defines all the variables used in the module.
#
class zimbra::params {

  $install_source = $::osfamily ? {
    'Debian' => $::operatingsystemrelease ? {
      '12.04' => 'https://files.zimbra.com/downloads/8.6.0_GA/zcs-NETWORK-8.6.0_GA_1153.UBUNTU12_64.20141215195643.tgz',
      '14.04' => 'https://files.zimbra.com/downloads/8.6.0_GA/zcs-NETWORK-8.6.0_GA_1153.UBUNTU14_64.20141215151218.tgz',
    },
    'RedHat' => $::operatingsystemmajrelease ? {
      '6' => 'https://files.zimbra.com/downloads/8.6.0_GA/zcs-NETWORK-8.6.0_GA_1153.RHEL6_64.20141215151258.tgz',
      '7' => 'https://files.zimbra.com/downloads/8.6.0_GA/zcs-NETWORK-8.6.0_GA_1153.RHEL7_64.20141215151204.tgz',
    },
  }

  $default_options = {
    'AVDOMAIN' => $::domain,
    'AVUSER' => "admin@${::domain}",
    'CREATEADMIN' => "admin@${::domain}",
    'CREATEDOMAIN' => $::domain,
    'DEFAULTLICENSEFILE' => '/opt/ZCSLicense.xml',
    'DOCREATEADMIN' => 'yes',
    'DOCREATEDOMAIN' => 'yes',
    'DOTRAINSA' => 'yes',
    'ENABLEDEFAULTBACKUP' => 'yes',
    'EXPANDMENU' => 'no',
    'HOSTNAME' => $::fqdn,
    'HTTPPORT' => '8080',
    'HTTPPROXY' => 'TRUE',
    'HTTPPROXYPORT' => '80',
    'HTTPSPORT' => '8443',
    'HTTPSPROXYPORT' => '443',
    'IMAPPORT' => '7143',
    'IMAPPROXYPORT' => '143',
    'IMAPSSLPORT' => '7993',
    'IMAPSSLPROXYPORT' => '993',
    'INSTALL_WEBAPPS' => 'service zimlet zimbra zimbraAdmin',
    'JAVAHOME' => '/opt/zimbra/java',
    'LDAPBESSEARCHSET' => 'set',
    'LDAPHOST' => $::fqdn,
    'LDAPPORT' => '389',
    'LDAPREPLICATIONTYPE' => 'master',
    'LDAPSERVERID' => '2',
    'LICENSEFILE' => '/opt/ZCSLicense.xml',
    'MAILBOXDMEMORY' => '256',
    'MAILPROXY' => 'TRUE',
    'MODE' => 'https',
    'MYSQLMEMORYPERCENT' => '30',
    'POPPORT' => '7110',
    'POPPROXYPORT' => '110',
    'POPSSLPORT' => '7995',
    'POPSSLPROXYPORT' => '995',
    'PROXYMODE' => 'https',
    'REMOVE' => 'no',
    'RUNARCHIVING' => 'no',
    'RUNAV' => 'yes',
    'RUNCBPOLICYD' => 'no',
    'RUNDKIM' => 'yes',
    'RUNSA' => 'yes',
    'RUNVMHA' => 'no',
    'SERVICEWEBAPP' => 'yes',
    'SMTPDEST' => "admin@${::domain}",
    'SMTPHOST' => $::domain,
    'SMTPNOTIFY' => 'yes',
    'SMTPSOURCE' => "admin@${::domain}",
    'SNMPNOTIFY' => 'yes',
    'SNMPTRAPHOST' => $::domain,
    'SPELLURL' => "http://${::domain}:7780/aspell.php",
    'STARTSERVERS' => 'yes',
    'SYSTEMMEMORY' => '1.0',
    'TRAINSAHAM' => "ham.wovy5mqk@${::domain}",
    'TRAINSASPAM' => "spam.jxpijaqd@${::domain}",
    'UIWEBAPPS' => 'yes',
    'UPGRADE' => 'no',
    'USESPELL' => 'yes',
    'VERSIONUPDATECHECKS' => 'TRUE',
    'VIRUSQUARANTINE' => "virus-quarantine.onyq1mop@${::domain}",
    'ZIMBRA_REQ_SECURITY' => 'yes',
    'ldap_bes_searcher_password' => 'z7lQDL0x',
    'ldap_dit_base_dn_config' => 'cn=zimbra',
    'ldap_nginx_password' => 'z7lQDL0x',
    'mailboxd_directory' => '/opt/zimbra/mailboxd',
    'mailboxd_keystore' => '/opt/zimbra/mailboxd/etc/keystore',
    'mailboxd_keystore_password' => '1BTJALYp3',
    'mailboxd_server' => 'jetty',
    'mailboxd_truststore' => '/opt/zimbra/java/jre/lib/security/cacerts',
    'mailboxd_truststore_password' => 'changeit',
    'postfix_mail_owner' => 'postfix',
    'postfix_setgid_group' => 'postdrop',
    'ssl_default_digest' => 'sha256',
    'zimbraBackupReportEmailRecipients' => "admin@${::domain}",
    'zimbraBackupReportEmailSender' => "admin@${::domain}",
    'zimbraDNSMasterIP' => '10.0.2.3',
    'zimbraDNSTCPUpstream' => 'no',
    'zimbraDNSUseTCP' => 'yes',
    'zimbraDNSUseUDP' => 'yes',
    'zimbraFeatureBriefcasesEnabled' => 'Enabled',
    'zimbraFeatureTasksEnabled' => 'Enabled',
    'zimbraIPMode' => 'ipv4',
    'zimbraMailProxy' => 'FALSE',
    'zimbraMtaMyNetworks' => '127.0.0.0/8 10.0.2.0/24 [::1]/128 [fe80::]/64',
    'zimbraPrefTimeZoneId' => 'America/Los_Angeles',
    'zimbraReverseProxyLookupTarget' => 'TRUE',
    'zimbraVersionCheckNotificationEmail' => "admin@${::domain}",
    'zimbraVersionCheckNotificationEmailFrom' => "admin@${::domain}",
    'zimbraVersionCheckSendNotifications' => 'TRUE',
    'zimbraWebProxy' => 'FALSE',
    'zimbra_ldap_userdn' => 'uid=zimbra,cn=admins,cn=zimbra',
    'zimbra_require_interprocess_security' => '1',
    'INSTALL_PACKAGES' => 'zimbra-core zimbra-ldap zimbra-logger zimbra-mta zimbra-dnscache zimbra-snmp zimbra-store zimbra-apache zimbra-spell zimbra-convertd zimbra-memcached zimbra-proxy ',
  }
}
